"""
Eclipse/VSCode Java 확장용 .classpath, .project 파일 생성.
"""

from pathlib import Path
from xml.sax.saxutils import escape

def _relative_or_abs(path: Path, project_root: Path) -> str:
    """
    project_root 기준 상대 경로로 표현 시도. 실패하면 절대 경로.
    Eclipse는 상대 경로를 선호함.
    """
    try:
        return str(path.relative_to(project_root)).replace("\\", "/")
    except ValueError:
        return str(path).replace("\\", "/")

def generate_classpath(
    project_root: Path,
    source_dirs: list[Path],
    output_dir: Path,
    jar_files: list[Path],
) -> str:
    """
    .classpath 파일 내용 생성.
    
    source_dirs: 소스 폴더 목록 (예: [src, tests])
    output_dir: 컴파일 결과 폴더 (.stoke/java/{target}/classes)
    jar_files: 외부 JAR 파일 목록 (.stoke/java/{target}/deps/*.jar)
    """
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<classpath>']

    # 소스 폴더들
    for src_dir in source_dirs:
        src_path = _relative_or_abs(src_dir, project_root)
        lines.append(f'    <classpathentry kind="src" path="{escape(src_path)}"/>')

    # 출력 폴더
    output_path = _relative_or_abs(output_dir, project_root)
    lines.append(f'    <classpathentry kind="output" path="{escape(output_path)}"/>')

    # 외부 JAR들
    for jar in jar_files:
        jar_path = _relative_or_abs(jar, project_root)
        lines.append(f'    <classpathentry kind="lib" path="{escape(jar_path)}"/>')

    # JRE 컨테이너 (IDE가 시스템 JDK 자동 사용)
    lines.append(
        '    <classpathentry kind="con" '
        'path="org.eclipse.jdt.launching.JRE_CONTAINER"/>'
    )

    lines.append('</classpath>')
    return "\n".join(lines) + "\n"


def generate_project(project_name: str) -> str:
    """
    .project 파일 내용 생성.
    """
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
    <name>{escape(project_name)}</name>
    <comment>Generated by stoke</comment>
    <projects>
    </projects>
    <buildSpec>
        <buildCommand>
            <name>org.eclipse.jdt.core.javabuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
    </buildSpec>
    <natures>
        <nature>org.eclipse.jdt.core.javanature</nature>
    </natures>
</projectDescription>
"""

def write_ide_files(
    project_root: Path,
    project_name: str,
    source_dirs: list[Path],
    output_dir: Path,
    jar_files: list[Path],
) -> tuple[Path, Path, bool, bool]:
    """
    .classpath와 .project를 프로젝트 루트에 저장.
    반환: (classpath_path, project_path, classpath_changed, project_changed)
    """
    classpath_content = generate_classpath(
        project_root, source_dirs, output_dir, jar_files
    )
    project_content = generate_project(project_name)
    classpath_path = project_root / ".classpath"
    project_path = project_root / ".project"

    classpath_changed = True
    if classpath_path.exists():
        old = classpath_path.read_text(encoding="utf-8")
        if old == classpath_content:
            classpath_changed = False
    if classpath_changed:
        classpath_path.write_text(classpath_content, encoding="utf-8")

    project_changed = True
    if project_path.exists():
        old = project_path.read_text(encoding="utf-8")
        if old == project_content:
            project_changed = False
    if project_changed:
        project_path.write_text(project_content, encoding="utf-8")

    return classpath_path, project_path, classpath_changed, project_changed