"""stoke completions <shell> -- bash/zsh/fish 자동완성 스크립트를 argparse 구조에서 직접 생성.

명령/플래그 목록은 생성 시점 기준으로 스냅샷됨 (다른 CLI들의 `<tool> completion <shell>`과 동일한 관례) --
stoke 버전을 올리면 `stoke completions <shell>`을 다시 실행해서 갱신해야 함.
"""
import argparse
import sys
from pathlib import Path

# target 이름을 동적으로 완성해야 하는 서브커맨드 (positional target 또는 --target 플래그)
_TARGET_POSITIONAL_COMMANDS = {"build", "clean", "watch", "run", "test", "hot-reload"}
_TARGET_FLAG_COMMANDS = {"add", "remove", "exec", "audit", "outdated", "sbom", "doctor"}

_HIDDEN_COMMANDS = {"complete-targets"}  # help=SUPPRESS만으로는 .choices에서 안 빠져서 따로 걸러냄

def _introspect(parser: argparse.ArgumentParser) -> dict[str, list[str]]:
    """{command_name: [flags...]} -- -h/--help은 어차피 항상 있어서 제외."""
    subparsers_action = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    result = {}
    for name, sub in subparsers_action.choices.items():
        if name in _HIDDEN_COMMANDS:
            continue
        flags = []
        for action in sub._actions:
            for opt in action.option_strings:
                if opt not in ("-h", "--help"):
                    flags.append(opt)
        result[name] = flags
    return result

def cmd_complete_targets() -> None:
    """`stoke complete-targets` -- 현재 stoke.toml의 타겟 이름을 한 줄씩 출력 (셸 완성 스크립트 전용, 조용히 실패)."""
    try:
        from stoke.config import load_config
        config = load_config()
    except Exception:
        return
    for name in config.targets:
        print(name)

def _generate_bash(commands: dict[str, list[str]]) -> str:
    command_names = " ".join(sorted(commands))
    lines = [
        "# stoke bash completion -- generated by `stoke completions bash`",
        "_stoke_completions() {",
        '    local cur="${COMP_WORDS[COMP_CWORD]}"',
        '    local prev="${COMP_WORDS[COMP_CWORD-1]}"',
        '    local cmd="${COMP_WORDS[1]}"',
        "",
        "    if [[ $COMP_CWORD -eq 1 ]]; then",
        f'        COMPREPLY=( $(compgen -W "{command_names}" -- "$cur") )',
        "        return 0",
        "    fi",
        "",
        "    local opts=\"\"",
        "    case \"$cmd\" in",
    ]
    for name, flags in sorted(commands.items()):
        lines.append(f'      "{name}") opts="{" ".join(flags)}" ;;')
    lines += [
        "    esac",
        "",
        '    if [[ "$cur" == -* ]]; then',
        '        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )',
        "        return 0",
        "    fi",
        "",
        '    case "$cmd" in',
        f'      {"|".join(sorted(_TARGET_POSITIONAL_COMMANDS))})',
        '        COMPREPLY=( $(compgen -W "$(stoke complete-targets 2>/dev/null)" -- "$cur") )',
        "        ;;",
        f'      {"|".join(sorted(_TARGET_FLAG_COMMANDS))})',
        '        if [[ "$prev" == "--target" ]]; then',
        '          COMPREPLY=( $(compgen -W "$(stoke complete-targets 2>/dev/null)" -- "$cur") )',
        "        fi",
        "        ;;",
        "    esac",
        "}",
        'complete -F _stoke_completions stoke',
        "",
    ]
    return "\n".join(lines)

def _generate_fish(commands: dict[str, list[str]]) -> str:
    lines = [
        "# stoke fish completion -- generated by `stoke completions fish`",
        "complete -c stoke -f",
    ]
    for name in sorted(commands):
        lines.append(f'complete -c stoke -n "__fish_use_subcommand" -a "{name}"')
    for name, flags in sorted(commands.items()):
        for flag in flags:
            long = flag.lstrip("-") if flag.startswith("--") else None
            short = flag.lstrip("-") if not flag.startswith("--") and flag.startswith("-") else None
            if long:
                lines.append(f'complete -c stoke -n "__fish_seen_subcommand_from {name}" -l {long}')
            elif short and len(short) == 1:
                lines.append(f'complete -c stoke -n "__fish_seen_subcommand_from {name}" -s {short}')
    target_cmds = " ".join(sorted(_TARGET_POSITIONAL_COMMANDS | _TARGET_FLAG_COMMANDS))
    lines.append(
        f'complete -c stoke -n "__fish_seen_subcommand_from {target_cmds}" '
        f'-a "(stoke complete-targets 2>/dev/null)"'
    )
    lines.append("")
    return "\n".join(lines)

def _generate_zsh(commands: dict[str, list[str]]) -> str:
    # 직접 짠 네이티브 zsh _arguments 스크립트는 이 환경에 zsh가 없어서 실제 검증을 못 했음 --
    # 대신 이미 실제로 테스트해서 동작 확인된 bash 스크립트를 bashcompinit으로 그대로 재사용.
    # (여러 CLI 툴이 실제로 쓰는, 잘 알려진 호환 방식)
    bash_script = _generate_bash(commands)
    lines = [
        "# stoke zsh completion -- generated by `stoke completions zsh`",
        "# Reuses the bash completion via bashcompinit (not a native zsh _arguments script) --",
        "# this environment had no zsh available to verify a hand-written one against, so this",
        "# reuses the bash script that *was* verified, instead of shipping something untested.",
        "autoload -U +X bashcompinit && bashcompinit",
        "",
        bash_script,
    ]
    return "\n".join(lines)

_GENERATORS = {"bash": _generate_bash, "fish": _generate_fish, "zsh": _generate_zsh}

_INSTALL_HINT = {
    "bash": "Add to ~/.bashrc: source <(stoke completions bash)\n  Or install system-wide: stoke completions bash | sudo tee /etc/bash_completion.d/stoke",
    "zsh": "Add to ~/.zshrc: source <(stoke completions zsh)",
    "fish": "stoke completions fish > ~/.config/fish/completions/stoke.fish",
}

def cmd_completions(shell: str) -> None:
    """stoke completions <bash|zsh|fish> -- 자동완성 스크립트를 stdout에 출력."""
    from stoke.cli import _build_parser

    generator = _GENERATORS.get(shell)
    if generator is None:
        print(f"Error: unknown shell '{shell}' (must be one of: {', '.join(_GENERATORS)})", file=sys.stderr)
        sys.exit(1)

    parser = _build_parser()
    commands = _introspect(parser)
    print(generator(commands))
    print(f"# {_INSTALL_HINT[shell]}", file=sys.stderr)
